/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import irrgarten.Directions;
import java.awt.Color;

/**
 *
 * @author roberto
 */
public class Cursors extends javax.swing.JDialog {

    private Directions direction; 
    //necesitas un atributo direction para que se almacene el valor al hacer click, que son las funciones de abajo
   
    public Cursors(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Color c = new Color(232,224,239);
        getContentPane().setBackground(c);
    }

    /**
     * Creates new form Cursors
     * @return 
     */
    public Directions getDirection(){
        //lo pones visible
        setVisible(true);
        
        //ahora te toca pulsar el boton, una vez lo pulses se va a guardar en direction el valor
        //por el pdf de P5 te explica lo de dispose un poco
        
        return direction;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RIGTH = new java.awt.Button();
        UP = new java.awt.Button();
        LEFT = new java.awt.Button();
        DOWN = new java.awt.Button();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(232, 224, 239));
        setBounds(new java.awt.Rectangle(750, 200, 50, 60));
        setForeground(new java.awt.Color(255, 255, 162));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        RIGTH.setActionCommand("RIGHT");
        RIGTH.setBackground(new java.awt.Color(200, 223, 217));
        RIGTH.setLabel("RIGHT");
        RIGTH.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                RIGTHComponentShown(evt);
            }
        });
        RIGTH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RIGTHActionPerformed(evt);
            }
        });

        UP.setActionCommand("UP");
        UP.setBackground(new java.awt.Color(200, 223, 217));
        UP.setLabel("UP");
        UP.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                UPComponentShown(evt);
            }
        });
        UP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPActionPerformed(evt);
            }
        });

        LEFT.setActionCommand("LEFT");
        LEFT.setBackground(new java.awt.Color(200, 223, 217));
        LEFT.setLabel("LEFT");
        LEFT.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                LEFTComponentShown(evt);
            }
        });
        LEFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LEFTActionPerformed(evt);
            }
        });

        DOWN.setActionCommand("DOWN");
        DOWN.setBackground(new java.awt.Color(200, 223, 217));
        DOWN.setLabel("DOWN");
        DOWN.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DOWNComponentShown(evt);
            }
        });
        DOWN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOWNActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(237, 217, 242));
        jLabel2.setFont(new java.awt.Font("Lato Heavy", 0, 15)); // NOI18N
        jLabel2.setText("Flechas de movimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LEFT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(RIGTH, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DOWN, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(108, 108, 108))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RIGTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LEFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(DOWN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Este no se ni como se ha creado ni lo que hace
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formMouseClicked

    private void RIGTHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RIGTHActionPerformed
        // TODO add your handling code here:
        direction=Directions.RIGHT;
        this.dispose();
    }//GEN-LAST:event_RIGTHActionPerformed

    private void DOWNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOWNActionPerformed
        // TODO add your handling code here:
        direction=Directions.DOWN;
        this.dispose();
    }//GEN-LAST:event_DOWNActionPerformed

    private void UPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPActionPerformed
        // TODO add your handling code here:
        direction=Directions.UP;
        this.dispose();
    }//GEN-LAST:event_UPActionPerformed

    private void LEFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LEFTActionPerformed
        // TODO add your handling code here:
        direction=Directions.LEFT;
        this.dispose();
    }//GEN-LAST:event_LEFTActionPerformed
//Estos que vienen a continuacion no sé para que siven
    
    
    
    private void UPComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_UPComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_UPComponentShown

    private void RIGTHComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_RIGTHComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_RIGTHComponentShown

    private void DOWNComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DOWNComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_DOWNComponentShown

    private void LEFTComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LEFTComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_LEFTComponentShown

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button DOWN;
    private java.awt.Button LEFT;
    private java.awt.Button RIGTH;
    private java.awt.Button UP;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
